# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
